spring:
  application:
    name: toy-aps-backend

  datasource:
    url: jdbc:mysql://database-2.clwoya2662ja.ap-northeast-2.rds.amazonaws.com:3306/toyaps
    username: admin
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: NON_NULL